server:
  port: 8888
spring:
  profiles:
    active: native #dev
  application:
    name: cloud-config-server
  cloud:
    config:
      name: pos-data
      server:
        native:
          search-locations: file:///D:/Retail/git-config-repo
        #git:
          #uri: file:///D:/Retail/git-config-repo



